// Generated by CoffeeScript 1.7.1
var Board;

Board = (function() {
  function Board(opts) {
    var i, j, _i, _j;
    this.numberCells = [];
    this.score = 0;
    for (i = _i = 0; _i < 4; i = ++_i) {
      this.numberCells[i] = [];
      for (j = _j = 0; _j < 4; j = ++_j) {
        this.numberCells[i][j] = new Number(0, i, j);
      }
    }
  }

  Board.prototype.generateOneNumber = function(showNumberAnimate) {
    var randNumberCell, randX, randY;
    if (this.noSpace()) {
      return false;
    }
    randX = +Math.floor(Math.random() * 4);
    randY = +Math.floor(Math.random() * 4);
    while (true) {
      randNumberCell = this.numberCells[randX][randY];
      if (randNumberCell.value === 0) {
        break;
      }
      randX = +Math.floor(Math.random() * 4);
      randY = +Math.floor(Math.random() * 4);
    }
    randNumberCell.value = Math.random() < 0.9 ? 2 : 4;
    if (typeof showNumberAnimate === "function") {
      showNumberAnimate(randNumberCell);
    }
    return true;
  };

  Board.prototype.updateAllcells = function(showOneNumber) {
    var cell, rowCells, _i, _j, _len, _len1, _ref;
    _ref = this.numberCells;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      rowCells = _ref[_i];
      for (_j = 0, _len1 = rowCells.length; _j < _len1; _j++) {
        cell = rowCells[_j];
        cell.merged = false;
        showOneNumber(cell);
      }
    }
  };

  Board.prototype.updateCell = function(fx, fy, tx, ty, moveCellAnimate) {
    var isSameCell, startCell, targetCell;
    startCell = this.numberCells[fx][fy];
    targetCell = this.numberCells[tx][ty];
    isSameCell = startCell.value === targetCell.value;
    if (targetCell.value === 0 || isSameCell) {
      if (!this.noBlock(startCell, targetCell)) {
        return false;
      }
      if (isSameCell) {
        if (targetCell.merged) {
          return false;
        }
        this.score += startCell.value;
        targetCell.merged = true;
      }
      targetCell.value += startCell.value;
      startCell.value = 0;
      moveCellAnimate(startCell, targetCell);
      return true;
    }
    return false;
  };

  Board.prototype.updateCell = function(fx, fy, tx, ty, moveCellAnimate) {
    var startCell, targetCell;
    startCell = this.numberCells[fx][fy];
    targetCell = this.numberCells[tx][ty];
    if (targetCell.value === 0 && this.noBlock(startCell, targetCell)) {
      moveCellAnimate(startCell, targetCell);
      targetCell.value = startCell.value;
      startCell.value = 0;
      return true;
    } else if (targetCell.value === startCell.value && this.noBlock(startCell, targetCell && !targetCell.merged)) {
      moveCellAnimate(startCell, targetCell);
      targetCell.value += startCell.value;
      targetCell.merged = true;
      this.score += startCell.value;
      startCell.value = 0;
      return true;
    }
    return false;
  };

  Board.prototype.noSpace = function() {
    var i, j, _i, _j;
    for (i = _i = 0; _i < 4; i = ++_i) {
      for (j = _j = 0; _j < 4; j = ++_j) {
        if (this.numberCells[i][j].value === 0) {
          return false;
        }
      }
    }
    return true;
  };

  Board.prototype.canMoveLeft = function() {
    var curCell, i, j, nextCell, _i, _j;
    for (i = _i = 0; _i < 4; i = ++_i) {
      for (j = _j = 1; _j < 4; j = ++_j) {
        nextCell = this.numberCells[i][j - 1];
        curCell = this.numberCells[i][j];
        if (nextCell.value === 0 || curCell.value === nextCell.value) {
          return true;
        }
      }
    }
    return false;
  };

  Board.prototype.canMoveRight = function() {
    var curCell, i, j, nextCell, _i, _j;
    for (i = _i = 0; _i < 4; i = ++_i) {
      for (j = _j = 3; _j > 0; j = --_j) {
        nextCell = this.numberCells[i][j];
        curCell = this.numberCells[i][j - 1];
        if (nextCell.value === 0 || curCell.value === nextCell.value) {
          return true;
        }
      }
    }
    return false;
  };

  Board.prototype.canMoveUp = function() {
    var curCell, i, j, nextCell, _i, _j;
    for (j = _i = 0; _i < 4; j = ++_i) {
      for (i = _j = 1; _j < 4; i = ++_j) {
        nextCell = this.numberCells[i - 1][j];
        curCell = this.numberCells[i][j];
        if (nextCell.value === 0 || curCell.value === nextCell.value) {
          return true;
        }
      }
    }
    return false;
  };

  Board.prototype.canMoveDown = function() {
    var curCell, i, j, nextCell, _i, _j;
    for (j = _i = 0; _i < 4; j = ++_i) {
      for (i = _j = 3; _j > 0; i = --_j) {
        nextCell = this.numberCells[i][j];
        curCell = this.numberCells[i - 1][j];
        if (nextCell.value === 0 || curCell.value === nextCell.value) {
          return true;
        }
      }
    }
    return false;
  };

  Board.prototype.noBlock = function(start, end) {
    var x, x1, x2, y, y1, y2, _i, _j;
    if (start.x === end.x) {
      x = start.x;
      if (start.y < end.y) {
        y1 = start.y + 1;
        y2 = end.y;
      } else {
        y1 = end.y + 1;
        y2 = start.y;
      }
      for (y = _i = y1; y1 <= y2 ? _i < y2 : _i > y2; y = y1 <= y2 ? ++_i : --_i) {
        return this.numberCells[x][y] !== 0;
      }
    } else {
      y = start.y;
      if (start.x < end.x) {
        x1 = start.x + 1;
        x2 = end.x;
      } else {
        x1 = end.x + 1;
        x2 = start.x;
      }
      for (x = _j = x1; x1 <= x2 ? _j < x2 : _j > x2; x = x1 <= x2 ? ++_j : --_j) {
        return this.numberCells[x][y] !== 0;
      }
    }
    return true;
  };

  Board.prototype.noMove = function() {
    if (this.canMoveLeft || this.canMoveRight || this.canMoveUp || this.canMoveDown) {
      return false;
    } else {
      return true;
    }
  };

  Board.prototype.moveLeft = function(moveCellAnimate) {
    var i, j, k, _i, _j, _k;
    if (!this.canMoveLeft()) {
      return false;
    }
    for (i = _i = 0; _i < 4; i = ++_i) {
      for (j = _j = 1; _j < 4; j = ++_j) {
        if (this.numberCells[i][j].value !== 0) {
          for (k = _k = 0; 0 <= j ? _k < j : _k > j; k = 0 <= j ? ++_k : --_k) {
            if (this.updateCell(i, j, i, k, moveCellAnimate)) {
              break;
            }
          }
        }
      }
    }
    return true;
  };

  Board.prototype.moveRight = function(moveCellAnimate) {
    var i, j, k, _i, _j, _k;
    if (!this.canMoveRight()) {
      return false;
    }
    for (i = _i = 0; _i < 4; i = ++_i) {
      for (j = _j = 2; _j >= 0; j = --_j) {
        if (this.numberCells[i][j].value !== 0) {
          for (k = _k = 3; 3 <= j ? _k < j : _k > j; k = 3 <= j ? ++_k : --_k) {
            if (this.updateCell(i, j, i, k, moveCellAnimate)) {
              break;
            }
          }
        }
      }
    }
    return true;
  };

  Board.prototype.moveUp = function(moveCellAnimate) {
    var i, j, k, _i, _j, _k;
    if (!this.canMoveUp()) {
      return false;
    }
    for (j = _i = 0; _i < 4; j = ++_i) {
      for (i = _j = 1; _j < 4; i = ++_j) {
        if (this.numberCells[i][j].value !== 0) {
          for (k = _k = 0; 0 <= i ? _k < i : _k > i; k = 0 <= i ? ++_k : --_k) {
            if (this.updateCell(i, j, k, j, moveCellAnimate)) {
              break;
            }
          }
        }
      }
    }
    return true;
  };

  Board.prototype.moveDown = function(moveCellAnimate) {
    var i, j, k, _i, _j, _k;
    if (!this.canMoveDown()) {
      return false;
    }
    for (j = _i = 0; _i < 4; j = ++_i) {
      for (i = _j = 2; _j >= 0; i = --_j) {
        if (this.numberCells[i][j].value !== 0) {
          for (k = _k = 3; 3 <= i ? _k < i : _k > i; k = 3 <= i ? ++_k : --_k) {
            if (this.updateCell(i, j, k, j, moveCellAnimate)) {
              break;
            }
          }
        }
      }
    }
    return true;
  };

  return Board;

})();
