// Generated by CoffeeScript 1.7.1
require.config({
  baseUrl: '/scripts',
  paths: {
    jQuery: 'lib/jquery-1.9.0'
  },
  shim: {
    jQuery: {
      exports: 'jQuery'
    }
  }
});

require(['jQuery', 'App2048'], function($, App) {
  $(function() {
    new App('level0');
  });
});
