// Generated by CoffeeScript 1.7.1
define(function() {
  'use strict';
  var Number, bgColors, dynasty;
  dynasty = ['', '夏', '商', '周', '秦', '汉', '三国', '晋', '隋', '唐', '宋', '元', '明', '清', '民国', 'PRC'];
  bgColors = ['transparent', '#eee4da', '#ede0c8', '#f2b179', '#f59563', '#f67c5f', '#f65e3b', '#edcf72', '#edcc61', '#9c0', '#33b5e5', '#09c', '#a6c', '#93c', '#2E4E7E', '#FF2121'];
  return Number = (function() {
    function Number(value, x, y) {
      this.value = value;
      this.x = x;
      this.y = y;
      this.merged = false;
    }

    Number.prototype.getColor = function() {
      if (this.value <= 4) {
        return '#776e65';
      } else {
        return '#fff';
      }
    };

    Number.prototype.getBgColor = function() {
      return bgColors[Math.ceil(Math.log2(this.value))];
    };

    Number.prototype.getText = function() {
      return dynasty[Math.ceil(Math.log2(this.value))];
    };

    Number.prototype.getFontSize = function() {
      if (this.value === 64 || this.value === 16384) {
        return 49;
      } else {
        return 60;
      }
    };

    Number.prototype.toString = function() {
      return JSON.stringify(this);
    };

    return Number;

  })();
});
